2024-12-17 10:59:07,733 - datamanager.sqliteDataManager - ERROR - Error adding movie: 'link' is an invalid keyword argument for Movie
Traceback (most recent call last):
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/popcornPickerV2/datamanager/sqliteDataManager.py", line 56, in add_movie
    new_movie = Movie(**movie_data)
                ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 571, in _initialize_instance
    with util.safe_reraise():
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 569, in _initialize_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/decl_base.py", line 2177, in _declarative_constructor
    raise TypeError(
TypeError: 'link' is an invalid keyword argument for Movie
2024-12-17 13:16:33,042 - datamanager.sqliteDataManager - ERROR - Key Error: 'imdbID'
Traceback (most recent call last):
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/popcornPickerV2/utilities.py", line 26, in retrieve_all_movie_data
    imdb_id = movie_info["imdbID"]
              ~~~~~~~~~~^^^^^^^^^^
KeyError: 'imdbID'
2024-12-17 13:23:50,723 - datamanager.sqliteDataManager - ERROR - Key Error: 'imdbID'
Traceback (most recent call last):
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/popcornPickerV2/utilities.py", line 21, in retrieve_all_movie_data
    imdb_id = movie_info["imdbID"]
              ~~~~~~~~~~^^^^^^^^^^
KeyError: 'imdbID'
2024-12-17 13:45:24,278 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Superman
2024-12-17 13:47:30,988 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Superman
2024-12-17 13:47:31,001 - datamanager.sqliteDataManager - WARNING - Movie 'Superman' already exists for user 1.
2024-12-17 13:47:48,322 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Superman
2024-12-17 13:47:48,326 - datamanager.sqliteDataManager - WARNING - Movie 'Superman' already exists for user 1.
2024-12-17 13:47:57,057 - datamanager.sqliteDataManager - ERROR - Movie not found or invalid title: jasdfkjlandsg
2024-12-17 13:47:57,058 - datamanager.sqliteDataManager - ERROR - Failed to fetcha data for movie: jasdfkjlandsg
2024-12-17 13:48:06,920 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Salamander
2024-12-17 13:48:06,933 - datamanager.sqliteDataManager - INFO - Movie Salamander added successfully for user 1
2024-12-17 13:55:14,689 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Hubert und Staller
2024-12-17 13:55:14,715 - datamanager.sqliteDataManager - INFO - Movie Hubert und Staller - Unter Wölfen added successfully for user 1
2024-12-17 13:55:30,457 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Pitch Black
2024-12-17 13:55:30,464 - datamanager.sqliteDataManager - INFO - Movie Pitch Black added successfully for user 1
2024-12-17 13:55:57,569 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Wild things
2024-12-17 13:55:57,580 - datamanager.sqliteDataManager - INFO - Movie Wild Things added successfully for user 1
2024-12-17 14:07:39,560 - datamanager.sqliteDataManager - ERROR - Movie not found or invalid title: hafgsags
2024-12-17 14:07:39,561 - datamanager.sqliteDataManager - ERROR - Failed to fetcha data for movie: hafgsags
2024-12-17 14:25:09,695 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Love at first sight
2024-12-17 14:25:09,713 - datamanager.sqliteDataManager - INFO - Movie Love at First Sight added successfully for user 2
2024-12-17 14:25:24,990 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Retribution
2024-12-17 14:25:25,005 - datamanager.sqliteDataManager - INFO - Movie Retribution added successfully for user 2
2024-12-17 14:45:56,399 - datamanager.sqliteDataManager - INFO - Movie with ID 4 deleted successfully.
2024-12-17 14:59:06,734 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Rabbit Proof Fence
2024-12-17 14:59:06,748 - datamanager.sqliteDataManager - INFO - Movie Rabbit-Proof Fence added successfully for user 1
2024-12-17 21:57:31,452 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Scary Movie
2024-12-17 21:57:31,468 - datamanager.sqliteDataManager - INFO - Movie Scary Movie added successfully for user 1
2024-12-17 21:57:41,337 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Scarface
2024-12-17 21:57:41,350 - datamanager.sqliteDataManager - INFO - Movie Scarface added successfully for user 1
2024-12-17 22:16:45,566 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: tatort
2024-12-17 22:16:45,573 - datamanager.sqliteDataManager - INFO - Movie Tatort added successfully for user 2
2024-12-17 22:16:57,131 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Hubert und staller
2024-12-17 22:16:57,139 - datamanager.sqliteDataManager - INFO - Movie Hubert und Staller - Unter Wölfen added successfully for user 2
2024-12-17 22:17:08,674 - datamanager.sqliteDataManager - ERROR - Movie not found or invalid title: land krimi
2024-12-17 22:17:08,675 - datamanager.sqliteDataManager - ERROR - Failed to fetcha data for movie: land krimi
2024-12-17 22:17:21,148 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Goldmember
2024-12-17 22:17:21,158 - datamanager.sqliteDataManager - INFO - Movie Austin Powers in Goldmember added successfully for user 2
2024-12-17 22:17:35,456 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Joker
2024-12-17 22:17:35,467 - datamanager.sqliteDataManager - INFO - Movie Joker added successfully for user 3
2024-12-17 22:17:55,398 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Goldeneye
2024-12-17 22:17:55,410 - datamanager.sqliteDataManager - INFO - Movie GoldenEye added successfully for user 3
2024-12-17 22:18:12,938 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Friends
2024-12-17 22:18:12,946 - datamanager.sqliteDataManager - INFO - Movie Friends added successfully for user 4
2024-12-17 22:21:05,021 - datamanager.sqliteDataManager - INFO - Movie with ID 10 deleted successfully.
2024-12-17 22:52:52,118 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: 300
2024-12-17 22:52:52,132 - datamanager.sqliteDataManager - INFO - Movie 300 added successfully for user 11
2024-12-18 09:31:04,633 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Inglorious bastards
2024-12-18 09:31:04,641 - datamanager.sqliteDataManager - INFO - Movie The Inglorious Bastards added successfully for user 12
2024-12-18 09:31:28,476 - datamanager.sqliteDataManager - INFO - Movie with ID 23 deleted successfully.
2024-12-18 10:15:20,676 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: gone in 60 seconds
2024-12-18 10:15:20,689 - datamanager.sqliteDataManager - INFO - Movie Gone in 60 Seconds added successfully for user 13
2024-12-18 10:15:42,694 - datamanager.sqliteDataManager - ERROR - Error updating movie: (builtins.ValueError) could not convert string to float: 'i can edit'
[SQL: UPDATE movies SET title=?, year=?, rating=? WHERE movies.id = ?]
[parameters: [{'rating': 'i can edit', 'year': 'that', 'title': 'crazy', 'movies_id': 7}]]
Traceback (most recent call last):
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 1476, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "lib/sqlalchemy/cyextension/processors.pyx", line 27, in sqlalchemy.cyextension.processors.to_float
ValueError: could not convert string to float: 'i can edit'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/popcornPickerV2/datamanager/sqliteDataManager.py", line 133, in update_movie
    self.db.session.commit()
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4487, in _flush
    with util.safe_reraise():
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1821, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/Users/mattwilliams/PycharmProjects/popcornPickerV2/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 1476, in _init_compiled
    flattened_processors[key](compiled_params[key])
  File "lib/sqlalchemy/cyextension/processors.pyx", line 27, in sqlalchemy.cyextension.processors.to_float
sqlalchemy.exc.StatementError: (builtins.ValueError) could not convert string to float: 'i can edit'
[SQL: UPDATE movies SET title=?, year=?, rating=? WHERE movies.id = ?]
[parameters: [{'rating': 'i can edit', 'year': 'that', 'title': 'crazy', 'movies_id': 7}]]
2024-12-18 10:16:20,084 - datamanager.sqliteDataManager - INFO - Movie with ID 7 deleted successfully.
2024-12-18 10:16:35,378 - datamanager.sqliteDataManager - INFO - Successfully retrieved movie data for: Australia
2024-12-18 10:16:35,393 - datamanager.sqliteDataManager - INFO - Movie Australia added successfully for user 1
